# Generated by Django 3.2.9 on 2021-11-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201109_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtype',
            name='blog_count',
            field=models.IntegerField(default=0),
        ),
    ]
